version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      SDK_KEY: "${SDK_KEY}"
    entrypoint: ["java", "-jar", "app.jar"]
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    depends_on:
      - redis
